[package]
name = "text_in_images"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
native-dialog = "0.6.3"
simple_bar = "0.1.6"
